//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPDTSystmAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pro_Rata_Registration_Subject_List
    {
        public System.Guid ID { get; set; }
        public string Pro_Rata_Registration_Id { get; set; }
        public string Allow_Subject_Name { get; set; }
        public string Date_Time { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
