//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPDTSystmAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regular_Registration_Data
    {
        public System.Guid ID { get; set; }
        public string Semester_Id { get; set; }
        public string Semester_Name { get; set; }
        public string Payment_Start_Date { get; set; }
        public string Payment_End_Date { get; set; }
        public string Semester_Start_Date { get; set; }
        public string Semester_End_Date { get; set; }
        public string Semester_Fee { get; set; }
        public string Late_Payment_Date_From { get; set; }
        public string Late_Payment_Date_To { get; set; }
        public string Late_Payment_Fee { get; set; }
        public string Date_Time { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
