//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPDTSystmAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repeat_Registration_Data
    {
        public List<Repeat_Registration_Subject_List> Repeat_Registration_Subject_List {
            get;
            set;
        }
        public System.Guid ID { get; set; }
        public string Semester_Id { get; set; }
        public string Repeat_Registration_Start_Date { get; set; }
        public string Repeat_Registration_End_Date { get; set; }
        public string Repeat_Fee { get; set; }
        public string Date_Time { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
