//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPDTSystmAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BPDTSysEntities : DbContext
    {
        public BPDTSysEntities()
            : base("name=BPDTSysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pro_Rata_Registration_Data> Pro_Rata_Registration_Data { get; set; }
        public virtual DbSet<Pro_Rata_Registration_Subject_List> Pro_Rata_Registration_Subject_List { get; set; }
        public virtual DbSet<Regular_Registration_Data> Regular_Registration_Data { get; set; }
        public virtual DbSet<Repeat_Registration_Data> Repeat_Registration_Data { get; set; }
        public virtual DbSet<Repeat_Registration_Subject_List> Repeat_Registration_Subject_List { get; set; }
        public virtual DbSet<Users_List> Users_List { get; set; }
    }
}
