//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPDTSystmAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_List
    {
        public System.Guid ID { get; set; }
        public string Index_No { get; set; }
        public string Student_Name { get; set; }
        public string Temp_Password { get; set; }
        public string Student_Type { get; set; }
        public string Course { get; set; }
        public string Email { get; set; }
        public string Date_Time { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
